### ISSUE TITLE
[Question] Extract JSON payload from In-app messages 

### ISSUE THREAD

**Issue by nksaroj** [adobe/aepsdk-messaging-android#218]
We would like to display the in-app payload that's gets sent out from AJO as JSON payload without any HTML contents so we can design our UI with native framework without needing to use Webview.

I tried to use MessagingDelegate interface and there are no public method to extract payload. 
Only option I could see assign the FullscreenMessage and then read the message with JavaScript which looks bad.

Have you got any delegate to extract the JSON payload?

**Comment by rymorale** [comment]
hi @nksaroj, apologies for missing this question. Do you still have a need to receive the in-app payload as a JSON? If so, could you open a ticket with your customer care representative so we can get this feature request prioritized?

Thanks,
Ryan
