### ISSUE TITLE
adb_clr_icon ignored in basic push notifications

### ISSUE THREAD

**Issue by emilrowland** [adobe/aepsdk-messaging-android#269]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-places-android/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

When sending notifications according to the payload defined here: https://developer.adobe.com/client-sdks/resources/reference/push-notifications/templates/basic/ the color attribute adb_clr_icon is ignored and instead a system default color is used.

### Environment

OS: Android 14
Device: Samsung S23

### Steps to reproduce

1. Send a push notification with an transparant **adb_icon** and select a background color with **adb_clr_icon**
2. Device receives a notification with the correct icon but the background is a system default and not the specified **adb_clr_icon** color

### Current behavior

The behavior now is that the background color of the notification is using a system default.

### Expected behavior

That the color selected by **adb_clr_icon** should be in use as the background color. Acording to documentation https://developer.adobe.com/client-sdks/resources/reference/push-notifications/templates/basic/

**Comment by emilrowland** [comment]
Should follow these guidelines from Google https://developer.android.com/design/ui/mobile/guides/home-screen/notifications#apply-icon-color

**Comment by spoorthipujariadobe** [comment]
Hi @emilrowland ,
Push templates are not currently supported by Messaging SDK. The documentation you linked is for Campaign Classic. We will add a note to the docs with the clarification.

Regards,
Spoorthi Pujari
